#!/bin/bash

rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 1 -model my_object01
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 3 -model my_object02
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 5 -model my_object04
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 7 -model my_object05
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 9 -model my_object06
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 11 -model my_object07
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 13 -model my_object08
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 15 -model my_object09
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 17 -model my_object10
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 19 -model my_object11
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 21 -model my_object12
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 23 -model my_object13
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 25 -model my_object14
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 27 -model my_object15
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 29 -model my_object16
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 31 -model my_object17
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 33 -model my_object18
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 35 -model my_object19
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 37 -model my_object20
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 39 -model my_object21
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 41 -model my_object22
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 43 -model my_object23
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 45 -model my_object24
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 47 -model my_object25
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 49 -model my_object26
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 48 -y 50 -model my_object27
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 46 -y 50 -model my_object28
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 44 -y 50 -model my_object29
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 42 -y 50 -model my_object30
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 40 -y 50 -model my_object31
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 38 -y 50 -model my_object32
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 36 -y 50 -model my_object33
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 34 -y 50 -model my_object34
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 32 -y 50 -model my_object35
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 30 -y 50 -model my_object36
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 28 -y 50 -model my_object37
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 26 -y 50 -model my_object38
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 24 -y 50 -model my_object39
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 22 -y 50 -model my_object40
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 20 -y 50 -model my_object41
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 18 -y 50 -model my_object42
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 16 -y 50 -model my_object43
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 14 -y 50 -model my_object44
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 12 -y 50 -model my_object45
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 10 -y 50 -model my_object46
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 8 -y 50 -model my_object47
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 6 -y 50 -model my_object48
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 4 -y 50 -model my_object49
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 2 -y 50 -model my_object50
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 50 -model my_object51
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 48 -model my_object52
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 46 -model my_object53
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 44 -model my_object54
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 42 -model my_object55
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 40 -model my_object56
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 38 -model my_object57
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 36 -model my_object58
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 34 -model my_object59
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 32 -model my_object60
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 30 -model my_object61
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 28 -model my_object62
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 26 -model my_object63
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 24 -model my_object64
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 22 -model my_object65
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 20 -model my_object66
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 18 -model my_object67
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 16 -model my_object68
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 14 -model my_object69
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 12 -model my_object70
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 10 -model my_object71
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 8 -model my_object72
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 6 -model my_object73
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 4 -model my_object74
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 2 -model my_object75
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 0 -y 0 -model my_object76
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 2 -y 0 -model my_object77
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 4 -y 0 -model my_object77
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 6 -y 0 -model my_object78
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 8 -y 0 -model my_object79
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 10 -y 0 -model my_object80
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 12 -y 0 -model my_object81
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 14 -y 0 -model my_object82
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 16 -y 0 -model my_object83
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 18 -y 0 -model my_object84
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 20 -y 0 -model my_object85
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 22 -y 0 -model my_object86
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 24 -y 0 -model my_object87
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 26 -y 0 -model my_object88
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 28 -y 0 -model my_object89
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 30 -y 0 -model my_object90
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 32 -y 0 -model my_object91
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 34 -y 0 -model my_object92
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 36 -y 0 -model my_object93
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 38 -y 0 -model my_object94
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 40 -y 0 -model my_object95
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 42 -y 0 -model my_object96
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 44 -y 0 -model my_object97
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 46 -y 0 -model my_object98
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 48 -y 0 -model my_object99
rosrun gazebo_ros spawn_model -file $(pwd)/object.urdf -urdf -z 5 -x 50 -y 0 -model my_object100
